#!/usr/bin/env python3
"""Add buyer/supplier network entry points to generated public pages.

The main public HTML pages are regenerated by build.py on every Vercel deploy,
so these additions are applied afterwards rather than hand-editing generated HTML.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
ADMIN_PAGES = {"stock-admin.html", "deal-desk.html"}


def insert_once(path: Path, needle: str, insertion: str, marker: str) -> None:
    html = path.read_text(encoding="utf-8")
    if marker in html:
        print(f"network links already present: {path.name}")
        return
    if needle not in html:
        raise RuntimeError(f"Could not find network insertion point in {path.name}")
    html = html.replace(needle, insertion + needle, 1)
    path.write_text(html, encoding="utf-8")
    print(f"patched network links: {path.name}")


def patch_stock_alert_nav() -> None:
    """Put Stock Alerts in both desktop and mobile navigation on public pages."""
    needle = '>Buy stock</a><a href="/obsolete-parts-sourcing.html"'
    replacement = '>Buy stock</a><a href="/buyer-alerts.html">Stock Alerts</a><a href="/obsolete-parts-sourcing.html"'
    for path in ROOT.glob("*.html"):
        if path.name in ADMIN_PAGES:
            continue
        html = path.read_text(encoding="utf-8")
        if '/buyer-alerts.html">Stock Alerts</a>' in html:
            continue
        if needle not in html:
            continue
        html = html.replace(needle, replacement)
        path.write_text(html, encoding="utf-8")
        print(f"patched Stock Alerts nav: {path.name}")


def patch_home() -> None:
    path = ROOT / "index.html"
    html = path.read_text(encoding="utf-8")
    old_ctas = '<div class="hero-ctas"><a href="/sell-surplus.html" class="btn big">Sell your surplus</a><a href="/buy-stock.html" class="btn big ghost">Browse stock</a></div>'
    new_ctas = '<div class="hero-ctas"><a href="/sell-surplus.html" class="btn big">Sell your surplus</a><a href="/buy-stock.html" class="btn big ghost">Browse stock</a><a href="/buyer-alerts.html" class="btn big ghost">Stock alerts</a></div>'
    if old_ctas in html:
        html = html.replace(old_ctas, new_ctas, 1)
        path.write_text(html, encoding="utf-8")
        print("patched homepage Stock Alerts hero CTA")

    block = '''<section style="padding:2.8rem 0">
  <div class="wrap">
    <div class="sec-head">
      <h2>Join the Automation Outlet <span>network</span></h2>
      <p>Turn a one-off visit into an ongoing connection &mdash; whether you buy automation equipment, come across surplus stock, or both.</p>
    </div>
    <div class="paths" style="margin:0">
      <div class="path">
        <h3>AO <span>Stock Alerts</span></h3>
        <p>Tell us the brands, equipment and deal sizes you buy. We can contact you when matching PLCs, HMIs, drives and job lots become available &mdash; often before a public listing.</p>
        <a class="link" href="/buyer-alerts.html">Join AO Stock Alerts &rarr;</a>
      </div>
      <div class="path">
        <h3>Supplier <span>network</span></h3>
        <p>Regularly come across redundant automation equipment? Join our supplier network for future clearances, purchases and managed resale opportunities.</p>
        <a class="link" href="/supplier-network.html">Join supplier network &rarr;</a>
      </div>
    </div>
  </div>
</section>'''
    needle = '<section class="quote" style="padding:3.2rem 0">\n  <div class="wrap">\n    <div class="sec-head"><h2>Not sure where to <span>start?</span></h2>'
    insert_once(path, needle, block, '/buyer-alerts.html')


def patch_buy() -> None:
    block = '''<section class="quote" style="padding:3rem 0">
  <div class="wrap">
    <div class="sec-head">
      <div class="eyebrow">AO Stock Alerts</div>
      <h2>Want first look at <span>incoming stock?</span></h2>
      <p>Tell us the manufacturers, equipment and deal sizes you buy. We can put matching surplus stock in front of you when it arrives, including selected opportunities before wider marketing.</p>
    </div>
    <a href="/buyer-alerts.html" class="btn big">Join AO Stock Alerts</a>
    <p class="services-note" style="margin-top:1rem">No general newsletter &mdash; just relevant automation stock matched to your buying profile.</p>
  </div>
</section>'''
    needle = '<section style="padding:3.2rem 0"><div class="wrap"><div class="sec-head"><h2>Why buy <span>from us</span></h2>'
    insert_once(ROOT / "buy-stock.html", needle, block, '/buyer-alerts.html')


def patch_sell() -> None:
    block = '''<section class="quote" style="padding:3rem 0">
  <div class="wrap">
    <div class="sec-head">
      <h2>Not selling today? <span>Stay connected.</span></h2>
      <p>If your business regularly comes across redundant PLCs, HMIs, drives, panels or machinery, join our supplier network and contact us when the next opportunity appears.</p>
    </div>
    <a href="/supplier-network.html" class="btn big">Join supplier network</a>
    <p class="services-note" style="margin-top:1rem">Have stock available right now? Use the seller portal above for a specific assessment.</p>
  </div>
</section>'''
    needle = '<section class="brands">'
    insert_once(ROOT / "sell-surplus.html", needle, block, '/supplier-network.html')


def main() -> None:
    patch_home()
    patch_buy()
    patch_sell()
    patch_stock_alert_nav()


if __name__ == "__main__":
    main()

