#!/usr/bin/env python3
"""Add buyer/supplier network entry points to generated public pages.

The main public HTML pages are regenerated by build.py on every Vercel deploy,
so these additions are applied afterwards rather than hand-editing generated HTML.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent


def insert_once(path: Path, needle: str, insertion: str, marker: str) -> None:
    html = path.read_text(encoding="utf-8")
    if marker in html:
        print(f"network links already present: {path.name}")
        return
    if needle not in html:
        raise RuntimeError(f"Could not find network insertion point in {path.name}")
    html = html.replace(needle, insertion + needle, 1)
    path.write_text(html, encoding="utf-8")
    print(f"patched network links: {path.name}")


def patch_home() -> None:
    block = '''<section style="padding:2.8rem 0">
  <div class="wrap">
    <div class="sec-head">
      <h2>Join the Automation Outlet <span>network</span></h2>
      <p>Tell us whether you buy automation equipment, come across surplus stock, or both.</p>
    </div>
    <div class="paths" style="margin:0">
      <div class="path">
        <h3>Buyer <span>stock alerts</span></h3>
        <p>Tell us the brands and equipment you buy. We can contact you when matching PLCs, HMIs, drives and job lots come in &mdash; often before a public listing.</p>
        <a class="link" href="/buyer-alerts.html">Get stock alerts &rarr;</a>
      </div>
      <div class="path">
        <h3>Supplier <span>network</span></h3>
        <p>Regularly come across redundant automation equipment? Join our supplier network for future clearances, purchases and managed resale opportunities.</p>
        <a class="link" href="/supplier-network.html">Join supplier network &rarr;</a>
      </div>
    </div>
  </div>
</section>'''
    needle = '<section class="quote" style="padding:3.2rem 0">\n  <div class="wrap">\n    <div class="sec-head"><h2>Not sure where to <span>start?</span></h2>'
    insert_once(ROOT / "index.html", needle, block, '/buyer-alerts.html')


def patch_buy() -> None:
    block = '''<section class="quote" style="padding:3rem 0">
  <div class="wrap">
    <div class="sec-head">
      <h2>Want first look at <span>incoming stock?</span></h2>
      <p>Join our buyer network, tell us the brands and equipment you need, and we can contact you when relevant stock arrives.</p>
    </div>
    <a href="/buyer-alerts.html" class="btn big">Get stock alerts</a>
    <p class="services-note" style="margin-top:1rem">No general newsletter &mdash; just relevant automation stock matching your preferences.</p>
  </div>
</section>'''
    needle = '<section style="padding:3.2rem 0"><div class="wrap"><div class="sec-head"><h2>Why buy <span>from us</span></h2>'
    insert_once(ROOT / "buy-stock.html", needle, block, '/buyer-alerts.html')


def patch_sell() -> None:
    block = '''<section class="quote" style="padding:3rem 0">
  <div class="wrap">
    <div class="sec-head">
      <h2>Not selling today? <span>Stay connected.</span></h2>
      <p>If your business regularly comes across redundant PLCs, HMIs, drives, panels or machinery, join our supplier network and contact us when the next opportunity appears.</p>
    </div>
    <a href="/supplier-network.html" class="btn big">Join supplier network</a>
    <p class="services-note" style="margin-top:1rem">Have stock available right now? Use the seller portal above for a specific assessment.</p>
  </div>
</section>'''
    needle = '<section class="brands">'
    insert_once(ROOT / "sell-surplus.html", needle, block, '/supplier-network.html')


def main() -> None:
    patch_home()
    patch_buy()
    patch_sell()


if __name__ == "__main__":
    main()
