const plcApi = '/api/plc-audit';

function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmtDate(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});}
function statusClass(status){return status==='COMPLETE'?'good':status==='FAILED'?'bad':status==='REVIEW_REQUIRED'?'warn':'blue';}
function statusBadge(status){return `<span class="plc-badge ${statusClass(status)}">${esc(status||'UNKNOWN')}</span>`;}
async function api(action,{method='GET',body,id,confirmationRef}={}){const q=new URLSearchParams({action});if(id)q.set('id',id);if(confirmationRef)q.set('confirmationRef',confirmationRef);const res=await fetch(`${plcApi}?${q}`,{method,headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});const data=await res.json().catch(()=>({}));if(!res.ok){const error=new Error(data.error||'Request failed');error.status=res.status;error.code=data.code;throw error;}return data;}


// This locator is not a credential; the API always checks the customer session.
function rememberAuditRef(id,ref){try{if(ref)sessionStorage.setItem(`ao-plc-audit-ref:${id}`,ref);}catch{}}
function readAuditRef(id){try{return sessionStorage.getItem(`ao-plc-audit-ref:${id}`)||'';}catch{return '';}}

function initNav(){const t=document.getElementById('navToggle'),m=document.getElementById('mobileMenu');if(t&&m)t.addEventListener('click',()=>{const o=m.classList.toggle('open');t.setAttribute('aria-expanded',o?'true':'false');});}

async function initUpload(){const form=document.getElementById('plcUploadForm');if(!form)return;const fileInput=document.getElementById('plcProjectFile'),status=document.getElementById('uploadStatus'),bar=document.querySelector('#uploadProgress span'),submit=form.querySelector('button[type=submit]');form.addEventListener('submit',async e=>{e.preventDefault();const file=fileInput.files?.[0];if(!file)return;submit.disabled=true;status.textContent='Creating secure upload permission…';bar.style.width='5%';try{const created=await api('create-upload',{method:'POST',body:{filename:file.name,size:file.size,contentType:file.type||'application/octet-stream'}});bar.style.width='15%';status.textContent='Uploading directly to private object storage…';const upload=await fetch(created.upload.url,{method:'PUT',headers:created.upload.headers,body:file});if(!upload.ok)throw new Error(`Private upload failed (${upload.status})`);bar.style.width='85%';status.textContent='Upload complete. Queuing analysis…';const confirmed=await api('confirm-upload',{method:'POST',body:{id:created.job.id,confirmationRef:created.confirmationRef}});rememberAuditRef(created.job.id,created.confirmationRef);bar.style.width='100%';status.textContent=confirmed.job.status==='COMPLETE'?'Snapshot complete. Opening results…':'Project queued for analysis. Opening audit…';location.href=`/plc-audit/audits/${encodeURIComponent(created.job.id)}`;}catch(err){status.textContent=err.message;bar.style.width='0';submit.disabled=false;}});}

function metric(label,value){return `<div class="plc-metric"><b>${esc(value??'—')}</b><span>${esc(label)}</span></div>`;}
function confidenceBadge(value){const cls=value==='VERIFIED'?'good':value==='INFERRED'?'warn':'';return `<span class="plc-badge ${cls}">${esc(value||'UNKNOWN')}</span>`;}
function severityBadge(value){const severity=String(value||'INFO').toUpperCase();const cls=severity==='CRITICAL'||severity==='HIGH'?'bad':severity==='ATTENTION'||severity==='MEDIUM'?'warn':'blue';return `<span class="plc-badge ${cls}">${esc(severity)}</span>`;}
function infoValue(value,fallback='Not yet identified'){return esc(value||fallback);}
function optionalMetric(label,value){return metric(label,value===null||value===undefined?'—':value);}
function bulletList(items,empty='No additional items were returned.'){return (items||[]).length?`<ul class="plc-manager-list">${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`:`<p class="plc-help">${esc(empty)}</p>`;}
function renderSnapshot(result){
  if(!result)return '<div class="plc-empty">Structured Snapshot results are not available yet.</div>';
  const project=result.project||{},controller=result.controller||{},hardware=result.hardwareSummary||{},program=result.programBreakdown||{},maintenance=result.maintenanceSummary||{};
  const findings=(result.topFindings||[]).map(f=>`<div class="plc-finding"><div class="plc-actions" style="justify-content:space-between"><h4>${esc(f.title)}</h4><div class="plc-actions">${severityBadge(f.severity)}${confidenceBadge(f.confidence)}</div></div><p>${esc(f.summary)}</p>${(f.evidence||[]).length?`<ul class="plc-evidence-list">${f.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</div>`).join('');

  const managerSummary=`<div class="plc-card plc-manager-summary"><div class="plc-actions" style="justify-content:space-between;align-items:flex-start"><div><div class="plc-kicker">Maintenance snapshot</div><h2>${infoValue(maintenance.headline,'PLC project analysed')}</h2></div><div class="plc-actions">${maintenance.priority?severityBadge(maintenance.priority):''}${confidenceBadge(maintenance.confidence)}</div></div><div class="plc-manager-grid"><div><span>Manufacturer</span><strong>${infoValue(controller.manufacturer)}</strong></div><div><span>PLC family</span><strong>${infoValue(controller.family)}</strong></div><div><span>CPU / model</span><strong>${infoValue(controller.model)}</strong></div><div><span>Lifecycle</span><strong>${infoValue(maintenance.lifecycle,'Not yet assessed')}</strong></div></div></div>`;

  const identification=`<div class="plc-evidence" style="margin-top:1rem"><div class="plc-card"><div class="plc-kicker">PLC / controller identity</div><table class="plc-table" style="margin-top:.7rem"><tr><th>Manufacturer</th><td>${infoValue(controller.manufacturer)}</td></tr><tr><th>PLC family</th><td>${infoValue(controller.family)}</td></tr><tr><th>CPU / model</th><td>${infoValue(controller.model)}</td></tr><tr><th>Order number</th><td>${infoValue(controller.orderNumber)}</td></tr><tr><th>Firmware</th><td>${infoValue(controller.firmware)}</td></tr><tr><th>Safety CPU / logic</th><td>${infoValue(controller.safetyType,'Not yet assessed')}</td></tr></table></div><div class="plc-card"><div class="plc-kicker">Project / software identity</div><table class="plc-table" style="margin-top:.7rem"><tr><th>Project name</th><td>${infoValue(project.projectName)}</td></tr><tr><th>Platform</th><td>${infoValue(project.platform)}</td></tr><tr><th>Engineering software</th><td>${infoValue(project.engineeringSoftware)}</td></tr><tr><th>Project version</th><td>${infoValue(project.projectVersion)}</td></tr><tr><th>Analysis engine</th><td><span class="mono">${infoValue(result.engineVersion,'—')}</span></td></tr></table></div></div>`;

  const programSummary=`<div class="plc-card" style="margin-top:1rem"><div class="plc-actions" style="justify-content:space-between"><div><div class="plc-kicker">Program & hardware footprint</div><h3>What maintenance is dealing with</h3></div><span class="plc-badge blue">Snapshot</span></div><div class="plc-metrics" style="margin-top:1rem">${metric('Total blocks',result.blockCount)}${optionalMetric('OBs',program.organisationBlocks)}${optionalMetric('FBs',program.functionBlocks)}${optionalMetric('FCs',program.functions)}${optionalMetric('DBs',program.dataBlocks)}${optionalMetric('Safety blocks',program.safetyBlocks)}</div><div class="plc-metrics" style="margin-top:.75rem">${optionalMetric('Configured I/O',hardware.configuredIoPoints)}${optionalMetric('Digital inputs',hardware.digitalInputs)}${optionalMetric('Digital outputs',hardware.digitalOutputs)}${optionalMetric('Analogue inputs',hardware.analogueInputs)}${optionalMetric('Analogue outputs',hardware.analogueOutputs)}${optionalMetric('Remote I/O',hardware.remoteIoStations)}</div><div class="plc-banner" style="margin-top:1rem"><strong>Communications:</strong> ${(hardware.communications||[]).length?(hardware.communications||[]).map(esc).join(', '):'Not yet identified'}<br><strong>I/O mapping:</strong> ${infoValue(hardware.ioMappingStatus,'Not yet assessed')}</div></div>`;

  const maintenancePanel=`<div class="plc-evidence" style="margin-top:1rem"><div class="plc-card"><div class="plc-kicker">What this means for maintenance</div><h3>Manager takeaways</h3>${bulletList(maintenance.managerPoints,'No maintenance summary is available yet.')}</div><div class="plc-card"><div class="plc-kicker">Recommended next actions</div><h3>Where to focus effort</h3>${bulletList(maintenance.recommendedActions,'No action recommendations are available yet.')}</div></div>`;

  const activity=`<div class="plc-metrics" style="margin-top:1rem">${metric('Networks',result.networkCount)}${metric('Calls',result.callCount)}${metric('Writes',result.writeCount)}${metric('Multiple writers',result.multipleWriterCount)}${metric('Investigations',result.investigationCount)}${metric('Coverage',`${result.analysisCoveragePercent}%`)}</div>`;

  return `${managerSummary}${identification}${programSummary}${maintenancePanel}${activity}<div class="plc-evidence" style="margin-top:1rem"><div class="plc-card"><div class="plc-kicker">Top findings</div>${findings||'<p>No priority findings were returned.</p>'}</div><div class="plc-card"><div class="plc-kicker">Coverage & evidence</div><p style="margin:.7rem 0"><strong>Analysis coverage:</strong> ${esc(result.analysisCoveragePercent)}%</p><div class="plc-progress"><span style="width:${Math.max(0,Math.min(100,Number(result.analysisCoveragePercent)||0))}%"></span></div><p style="margin-top:1rem"><strong>Overall evidence:</strong> ${confidenceBadge(result.evidenceConfidence)}</p><p><strong>Supported:</strong> ${(result.supportedAreas||[]).map(esc).join(', ')||'—'}</p><p><strong>Unsupported:</strong> ${(result.unsupportedAreas||[]).map(esc).join(', ')||'—'}</p></div></div>`;
}

async function initAudit(missingRetries=0){const root=document.getElementById('auditRoot');if(!root)return;const parts=location.pathname.split('/').filter(Boolean);const id=parts[parts.length-1]||new URLSearchParams(location.search).get('id');try{const {audit}=await api('get',{id,confirmationRef:readAuditRef(id)});root.innerHTML=`<div class="plc-card"><div class="plc-actions" style="justify-content:space-between"><div><div class="plc-kicker">Audit ${esc(audit.id)}</div><h2>${esc(audit.filename)}</h2></div>${statusBadge(audit.status)}</div><table class="plc-table" style="margin-top:1rem"><tr><th>Platform</th><td>${esc(audit.detectedPlatform||'Pending analysis')}</td><th>Project version</th><td>${esc(audit.detectedProjectVersion||'Pending analysis')}</td></tr><tr><th>Created</th><td>${fmtDate(audit.createdAt)}</td><th>Completed</th><td>${fmtDate(audit.completedAt)}</td></tr></table></div><section style="padding:1.2rem 0">${renderSnapshot(audit.snapshotResult)}</section><div class="plc-card"><div class="plc-kicker">Next engineering step</div><h3>Need deeper engineering review?</h3><p>The automated Snapshot is a triage layer. A Small PLC Audit adds engineer review, investigation notes and a scoped written outcome.</p><div class="plc-actions" style="margin-top:1rem"><a class="btn" href="/contact.html?service=small-plc-audit">Request Small PLC Audit</a><a class="btn ghost" href="/contact.html?service=full-plc-audit">Request Full Engineering Audit</a><a class="btn ghost" href="/contact.html?service=legacy-modernisation-discovery">Start Modernisation Discovery</a></div></div><div class="plc-actions" style="margin-top:1rem"><a class="btn ghost" href="/plc-audit/dashboard">Back to dashboard</a>${audit.reportAvailable?'<button class="btn ghost" id="downloadReport">Private report download</button>':''}<button class="btn ghost" id="deleteAudit">Delete project</button></div><p class="plc-help">Uploaded source and any private report artifacts are deleted when you delete the project. The audit disappears from your dashboard; only minimal deletion metadata is retained for the service record.</p>`;document.getElementById('deleteAudit')?.addEventListener('click',async()=>{if(!confirm('Delete this PLC project and any private report files? The audit will be removed from your dashboard and this cannot be undone.'))return;await api('delete',{method:'DELETE',id:audit.id});location.href='/plc-audit/dashboard';});document.getElementById('downloadReport')?.addEventListener('click',async()=>{const d=await api('report-url',{id:audit.id});location.href=d.url;});if(['CREATED','UPLOADING','QUEUED','ANALYSING'].includes(audit.status))setTimeout(()=>initAudit(),3000);}catch(err){if(err.status===404&&err.code==='AUDIT_NOT_FOUND'&&missingRetries<10){root.innerHTML='<div class="plc-empty">Preparing your audit. Checking again shortly�</div>';setTimeout(()=>initAudit(missingRetries+1),3000);return;}root.innerHTML=`<div class="plc-empty">${esc(err.message)}</div>`;}}

async function initDashboard(){const root=document.getElementById('dashboardRoot');if(!root)return;try{const {audits}=await api('list');if(!audits.length){root.innerHTML='<div class="plc-empty">No PLC audits are linked to this customer session yet.<br><br><a class="btn" href="/plc-audit/upload">Run a free Snapshot</a></div>';return;}root.innerHTML=`<div class="plc-card"><table class="plc-table"><thead><tr><th>Project</th><th>Status</th><th>Platform</th><th>Created</th><th></th></tr></thead><tbody>${audits.map(a=>`<tr><td><strong>${esc(a.filename)}</strong><br><span class="mono" style="font-size:.75rem;color:var(--grey)">${esc(a.id)}</span></td><td>${statusBadge(a.status)}</td><td>${esc(a.detectedPlatform||'Pending')}</td><td>${fmtDate(a.createdAt)}</td><td><a href="/plc-audit/audits/${encodeURIComponent(a.id)}">Open →</a></td></tr>`).join('')}</tbody></table></div>`;}catch(err){root.innerHTML=`<div class="plc-empty">${esc(err.message)}</div>`;}}

document.addEventListener('DOMContentLoaded',()=>{initNav();initUpload();initAudit();initDashboard();});
