export const SITE = 'https://www.automation-outlet.co.uk';
export const collections = {
  all: {name:'Industrial automation parts', title:'Industrial Automation Parts for Sale UK', intro:'Browse current UK stock of new, used and surplus industrial automation equipment. Open an item for its exact part number, condition, price and buying options.', advice:'Match the complete manufacturer part number and revision before ordering. Check the individual listing for test status, included accessories and delivery details.', match:()=>true},
  siemens: {name:'Siemens parts', title:'Siemens PLCs and Automation Spares UK', intro:'Browse Siemens SIMATIC PLC processors, ET200 I/O and automation spares currently available from Automation Outlet.', advice:'Check the complete Siemens order number, including the suffix. S7-300, ET200S and ET200SP modules use different station arrangements; confirm the base or terminal unit and firmware requirements for your installation.', match:p=>/^siemens$/i.test(p.brand)},
  'allen-bradley': {name:'Allen-Bradley parts', title:'Allen-Bradley PLCs and Control Spares UK', intro:'Find Allen-Bradley controllers, I/O and control hardware from our current UK surplus stock.', advice:'Match the catalogue number and series, then check firmware, rack or expansion compatibility and included connectors. Open the listing to distinguish factory-sealed stock from opened or used equipment.', match:p=>/^allen[ -]bradley$/i.test(p.brand)},
  omron: {name:'Omron parts', title:'Omron PLCs and I/O Modules for Sale UK', intro:'Browse Omron SYSMAC PLC processors, expansion modules and industrial control spares from UK stock.', advice:'Check the CPU or module reference, supply voltage, input/output type and expansion compatibility. A power-up check does not establish that every channel or communication port has been tested; use the listing’s stated test details.', match:p=>/^omron$/i.test(p.brand)},
  'plc-processors': {name:'PLC processors', title:'Used and Surplus PLC Processors for Sale UK', intro:'Find PLC CPUs and controllers for maintenance, replacement spares and existing industrial control systems.', advice:'Before replacing a CPU, check the complete part number, hardware revision, firmware, memory and programming software requirements. Confirm whether any memory card or connectors shown are included; an existing machine programme is not implied.', match:p=>p.category==='PLC CPU'},
  'plc-io-modules': {name:'PLC I/O modules', title:'PLC Input and Output Modules for Sale UK', intro:'Browse digital and analogue PLC I/O modules, remote I/O and expansion hardware from current UK stock.', advice:'Match channel count, input/output type, signal range and supply voltage. For remote I/O, verify the station family and terminal/base unit. A standard output module must not be substituted for a safety-rated module.', match:p=>p.category==='PLC I/O module'},
  'drives-inverters': {name:'Drives and inverters', title:'Surplus Variable Speed Drives and Inverters UK', intro:'Browse variable speed drives, inverters and drive hardware available from Automation Outlet in the UK.', advice:'Check supply voltage, phase, rated current, motor power and the full drive reference. Confirm braking, communication and enclosure requirements for your application; settings and commissioning are specific to the machine.', match:p=>p.category==='Drive / inverter'},
};
export function html(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function slugify(value){return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);}
export function productSlug(p){return slugify([p.brand,p.partNumber].filter(Boolean).join('-'));}
export function available(p){return p.status==='active' && Number(p.quantity)>0 && p.issueState==='open';}
export function publicProducts(products){
  const sorted = products.filter(p=>['active','sold'].includes(p.status)&&productSlug(p)).sort((a,b)=>Number(available(b))-Number(available(a))||String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));
  const bySlug=new Map();
  for(const p of sorted) if(!bySlug.has(productSlug(p))) bySlug.set(productSlug(p),p);
  return [...bySlug.values()];
}
export function money(p){return p.priceGbp!==null && p.priceGbp!=='' && Number.isFinite(Number(p.priceGbp)) && Number(p.priceGbp)>0 ? Number(p.priceGbp).toFixed(2):null;}
export function json(value){return JSON.stringify(value).replace(/</g,'\\u003c');}
export function browseLinks(){return `<nav aria-label="Browse stock by manufacturer or type" class="browse-links">${Object.entries(collections).map(([slug,c])=>`<a href="${slug==='all'?'/parts':'/parts/'+slug}">${html(c.name)}</a>`).join('')}</nav>`;}
export function header(){return `<header><div class="wrap nav"><a href="/" class="logo logo-image" aria-label="Automation Outlet home"><img src="/ao-site-logo.svg" width="280" height="59" alt="Automation Outlet"></a><nav class="nav-links" aria-label="Main navigation"><a href="/buy-stock.html">Buy stock</a><a href="/parts">Browse parts</a><a href="/sell-surplus.html">Sell to us</a><a href="/buyer-alerts.html">Stock alerts</a><a href="/contact.html">Contact</a></nav><button class="nav-toggle" id="navToggle" aria-label="Open menu" aria-expanded="false" aria-controls="mobileMenu"><span></span><span></span><span></span></button></div><nav class="mobile-menu" id="mobileMenu" aria-label="Mobile navigation"><a href="/buy-stock.html">Search stock</a><a href="/parts">Browse all parts</a><a href="/sell-surplus.html">Sell to us</a><a href="/buyer-alerts.html">Stock alerts</a><a href="/obsolete-parts-sourcing.html">Source a part</a><a href="/contact.html">Contact</a></nav></header>`;}
export const menuScript = `<script>document.getElementById('navToggle').addEventListener('click',function(){const open=document.getElementById('mobileMenu').classList.toggle('open');this.setAttribute('aria-expanded',String(open));this.setAttribute('aria-label',open?'Close menu':'Open menu');});</script>`;
export const shopCss = `.browse-links{display:flex;flex-wrap:wrap;gap:.6rem;margin:1.2rem 0}.browse-links a{display:block;padding:.5rem .8rem;border:1px solid var(--line);border-radius:8px}.shop-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:1rem}.shop-card{min-width:0;padding:1.2rem;background:var(--navy-card);border:1px solid var(--line);border-radius:14px}.shop-card img{display:block;width:100%;height:210px;object-fit:contain;background:#fff;margin-bottom:1rem}.shop-card h2{font-size:1.4rem;overflow-wrap:anywhere}.shop-card p{margin:.8rem 0;color:var(--grey)}.shop-intro{max-width:800px;color:var(--grey);margin:1rem 0}.shop-heading{font-size:clamp(2rem,5vw,3.5rem);overflow-wrap:anywhere}`;
export function productCard(p){const price=money(p);return `<article class="shop-card"><a href="/stock/${productSlug(p)}">${p.imageUrl?`<img src="${html(p.imageUrl)}" alt="${html(p.title)}" loading="lazy" decoding="async">`:''}<h2>${html(p.title||p.partNumber)}</h2></a><p>${html(p.partNumber)}<br>${html(p.condition)} · ${html(p.quantity)} available</p><p>${price?'£'+price:'Enquire for price'}</p><a class="btn" href="/stock/${productSlug(p)}">View details &amp; buy</a></article>`;}
