export const SITE = 'https://www.automation-outlet.co.uk';
export const collections = {
  all: {name:'Industrial automation parts', title:'Industrial Automation Parts for Sale UK', intro:'Browse current UK stock of new, used and surplus industrial automation equipment. Open an item for its exact part number, condition, price and buying options.', advice:'Match the complete manufacturer part number and revision before ordering. Check the individual listing for test status, included accessories and delivery details.', match:()=>true},
  siemens: {name:'Siemens parts', title:'Siemens PLCs and Automation Spares UK', intro:'Browse Siemens SIMATIC PLC processors, ET200 I/O and automation spares currently available from Automation Outlet.', advice:'Check the complete Siemens order number, including the suffix. S7-300, ET200S and ET200SP modules use different station arrangements; confirm the base or terminal unit and firmware requirements for your installation.', match:p=>/^siemens$/i.test(p.brand)},
  'allen-bradley': {name:'Allen-Bradley parts', title:'Allen-Bradley PLCs and Control Spares UK', intro:'Find Allen-Bradley controllers, I/O and control hardware from our current UK surplus stock.', advice:'Match the catalogue number and series, then check firmware, rack or expansion compatibility and included connectors. Open the listing to distinguish factory-sealed stock from opened or used equipment.', match:p=>/^allen[ -]bradley$/i.test(p.brand)},
  omron: {name:'Omron parts', title:'Omron PLCs and I/O Modules for Sale UK', intro:'Browse Omron SYSMAC PLC processors, expansion modules and industrial control spares from UK stock.', advice:'Check the CPU or module reference, supply voltage, input/output type and expansion compatibility. A power-up check does not establish that every channel or communication port has been tested; use the listing’s stated test details.', match:p=>/^omron$/i.test(p.brand)},
  'plc-processors': {name:'PLC processors', title:'Used and Surplus PLC Processors for Sale UK', intro:'Find PLC CPUs and controllers for maintenance, replacement spares and existing industrial control systems.', advice:'Before replacing a CPU, check the complete part number, hardware revision, firmware, memory and programming software requirements. Confirm whether any memory card or connectors shown are included; an existing machine programme is not implied.', match:p=>p.category==='PLC CPU'},
  'plc-io-modules': {name:'PLC I/O modules', title:'PLC Input and Output Modules for Sale UK', intro:'Browse digital and analogue PLC I/O modules, remote I/O and expansion hardware from current UK stock.', advice:'Match channel count, input/output type, signal range and supply voltage. For remote I/O, verify the station family and terminal/base unit. A standard output module must not be substituted for a safety-rated module.', match:p=>p.category==='PLC I/O module'},
  'drives-inverters': {name:'Drives and inverters', title:'Surplus Variable Speed Drives and Inverters UK', intro:'Browse variable speed drives, inverters and drive hardware available from Automation Outlet in the UK.', advice:'Check supply voltage, phase, rated current, motor power and the full drive reference. Confirm braking, communication and enclosure requirements for your application; settings and commissioning are specific to the machine.', match:p=>p.category==='Drive / inverter'},
};
export function html(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function slugify(value){return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);}
export function productSlug(p){return slugify([p.brand,p.partNumber].filter(Boolean).join('-'));}
export function available(p){return p.status==='active' && Number(p.quantity)>0 && p.issueState==='open';}
export function publicProducts(products){
  const sorted = products.filter(p=>['active','sold'].includes(p.status)&&productSlug(p)).sort((a,b)=>Number(available(b))-Number(available(a))||String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));
  const bySlug=new Map();
  for(const p of sorted) if(!bySlug.has(productSlug(p))) bySlug.set(productSlug(p),p);
  return [...bySlug.values()];
}
export function money(p){return p.priceGbp!==null && p.priceGbp!=='' && Number.isFinite(Number(p.priceGbp)) && Number(p.priceGbp)>0 ? Number(p.priceGbp).toFixed(2):null;}
export function json(value){return JSON.stringify(value).replace(/</g,'\\u003c');}
export function browseLinks(){return `<nav aria-label="Browse stock by manufacturer or type" class="browse-links">${Object.entries(collections).map(([slug,c])=>`<a href="${slug==='all'?'/parts':'/parts/'+slug}">${html(c.name)}</a>`).join('')}</nav>`;}
export function header(){return `<header class="shop-header">
  <div class="wrap nav shop-nav">
    <a href="/" class="logo logo-image" aria-label="Automation Outlet home"><img src="/ao-site-logo.svg" width="280" height="59" alt="Automation Outlet"></a>
    <nav class="nav-links" aria-label="Main navigation"><a href="/buy-stock.html">Buy stock</a><a href="/parts">Browse parts</a><a href="/sell-surplus.html">Sell to us</a><a href="/buyer-alerts.html">Stock alerts</a><a href="/contact.html">Contact</a></nav>
    <div class="shop-tools"><a class="cart-link" href="/cart.html" aria-label="View basket"><span class="cart-icon" aria-hidden="true">🛒</span><span class="cart-label">Basket</span><span class="cart-count" data-cart-count>0</span></a><button class="nav-toggle" id="navToggle" aria-label="Open menu" aria-expanded="false" aria-controls="mobileMenu"><span></span><span></span><span></span></button></div>
  </div>
  <div class="shop-search-band"><div class="wrap"><form class="site-search" action="/buy-stock.html#stock" method="get" role="search"><label class="sr-only" for="sitePartSearch">Search stock</label><input id="sitePartSearch" name="q" type="search" placeholder="Search by part number, manufacturer or keyword" required><button type="submit" aria-label="Search">Search</button></form></div></div>
  <nav class="mobile-menu" id="mobileMenu" aria-label="Mobile navigation"><a href="/buy-stock.html">Search stock</a><a href="/parts">Browse all parts</a><a href="/sell-surplus.html">Sell to us</a><a href="/buyer-alerts.html">Stock alerts</a><a href="/obsolete-parts-sourcing.html">Source a part</a><a href="/contact.html">Contact</a></nav>
</header>`;}
export const menuScript = `<script>document.getElementById('navToggle')?.addEventListener('click',function(){const open=document.getElementById('mobileMenu').classList.toggle('open');this.setAttribute('aria-expanded',String(open));this.setAttribute('aria-label',open?'Close menu':'Open menu');});</script><script src="/shop-cart.js" defer></script>`;
export const shopCss = `.sr-only{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}.shop-header{background:rgba(6,14,31,.97)}.shop-nav{gap:1rem}.shop-tools{display:flex;align-items:center;gap:.7rem}.cart-link{display:inline-flex;align-items:center;gap:.35rem;color:var(--white);font-weight:700;padding:.45rem .7rem;border:1px solid var(--line);border-radius:9px}.cart-link:hover{border-color:var(--blue-bright)}.cart-icon{font-size:1.1rem}.cart-count{display:grid;place-items:center;min-width:21px;height:21px;padding:0 .3rem;border-radius:999px;background:var(--blue);color:#fff;font-size:.72rem}.shop-search-band{border-top:1px solid rgba(77,148,255,.08);background:var(--navy)}.site-search{max-width:none;display:flex;padding:.75rem 0;gap:.55rem}.site-search input{background:#fff;color:#071225;border-color:transparent;font-weight:600}.site-search input::placeholder{color:#66758a}.site-search button{flex:none;border:0;border-radius:9px;background:var(--blue);color:#fff;padding:0 1.25rem;font:700 1rem 'Barlow Condensed';text-transform:uppercase;letter-spacing:.05em;cursor:pointer}.browse-links{display:flex;flex-wrap:wrap;gap:.6rem;margin:1.2rem 0}.browse-links a{display:block;padding:.5rem .8rem;border:1px solid var(--line);border-radius:8px}.shop-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:1rem}.shop-card{min-width:0;padding:1rem;background:var(--navy-card);border:1px solid var(--line);border-radius:14px;display:flex;flex-direction:column}.shop-card-media{display:block;background:#fff;border-radius:10px;overflow:hidden;margin-bottom:.9rem}.shop-card img{display:block;width:100%;height:220px;object-fit:contain;background:#fff}.shop-card-brand{font-family:'IBM Plex Mono';font-size:.7rem;letter-spacing:.08em;text-transform:uppercase;color:var(--blue-bright);margin-bottom:.25rem}.shop-card h2{font-size:1.35rem;overflow-wrap:anywhere;text-transform:none;line-height:1.15}.shop-card-part{font-family:'IBM Plex Mono';font-size:.78rem;color:var(--grey);margin:.55rem 0}.shop-card-status{font-size:.82rem;font-weight:700;color:#8fe3b1}.shop-card-condition{font-size:.86rem;color:var(--grey);margin:.35rem 0}.shop-card-price{font-family:'Barlow Condensed';font-size:1.7rem;font-weight:800;margin:.45rem 0 .8rem}.shop-card .btn{margin-top:auto;text-align:center}.shop-intro{max-width:800px;color:var(--grey);margin:1rem 0}.shop-heading{font-size:clamp(2rem,5vw,3.5rem);overflow-wrap:anywhere}@media(max-width:900px){.shop-nav .nav-links{display:none}.shop-nav .nav-toggle{display:flex}}@media(max-width:640px){.shop-search-band .wrap{padding:0 12px}.site-search{padding:.55rem 0}.site-search input{padding:.72rem .75rem}.site-search button{padding:0 .85rem}.cart-label{display:none}.cart-link{padding:.4rem .5rem}.shop-card img{height:190px}}`;
export function productCard(p){const price=money(p);const live=available(p);const delivery=p.deliveryMode==="parcel"?"UK delivery £7.95 · free over £250":"Delivery quote required";return `<article class="shop-card"><a class="shop-card-media" href="/stock/${productSlug(p)}">${p.imageUrl?`<img src="${html(p.imageUrl)}" alt="${html(p.title||p.partNumber)}" loading="lazy" decoding="async">`:`<div style="height:220px;display:grid;place-items:center;color:#66758a">Image coming soon</div>`}</a><div class="shop-card-brand">${html(p.brand||'Industrial automation')}</div><a href="/stock/${productSlug(p)}"><h2>${html(p.title||p.partNumber)}</h2></a><div class="shop-card-part">${html(p.partNumber)}</div><div class="shop-card-status">${live?'● In stock – UK':'Currently unavailable'}</div><div class="shop-card-condition">${html(p.condition||'Condition stated')}</div><div class="shop-card-condition">${html(delivery)}</div><div class="shop-card-price">${price?'£'+price:'Enquire for price'}</div><a class="btn" href="/stock/${productSlug(p)}">View product</a></article>`;}
